# Generated by Django 3.1 on 2020-08-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20200805_1455"),
    ]

    operations = [
        migrations.AlterModelOptions(name="usuario", options={},),
        migrations.AlterModelManagers(name="usuario", managers=[],),
    ]
