# Generated by Django 3.1 on 2020-08-06 18:13

import app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_auto_20200806_1424"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[("objects", app.managers.UsuarioManager()),],
        ),
    ]
